<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPy3iek8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPy3iek8/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPy3iek8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPy3iek8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPy3iek8\appProdProjectContainer([
    'container.build_hash' => 'Py3iek8',
    'container.build_id' => 'd6997010',
    'container.build_time' => 1602329926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPy3iek8');
